
spring:
  cloud:
    gateway:
      routes:
        - id: clasificacion
          uri: lb://CLASIFICACION
          predicates:
            - Path=/clasificacion/**
          filters:
            - RewritePath=/clasificacion/(?<segment>.*), /${segment}


        - id: descripciones_minimas_route
          uri: lb://DESCRIPCIONES-MINIMAS
          predicates:
              - Path=/descripciones/**
          filters:
            - RewritePath=/descripciones/(?<segment>.*), /${segment}
